import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  site: 'https://imverica.com',
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'ru', 'uk', 'es'],
    routing: { prefixDefaultLocale: false }
  },
  // Sitemap is generated by src/pages/sitemap.xml.ts (hand-rolled to
  // avoid the @astrojs/sitemap × Astro 4 compatibility bug).
  integrations: [],
  // Output to dist/. Netlify will publish this directory once the cutover
  // happens in Phase 4. Until then the legacy index.html at repo root keeps
  // shipping.
  build: {
    assets: 'assets'
  },
  // Compress HTML output and prefetch on hover for snappy navigation.
  prefetch: true,
  compressHTML: true
});
